[project]
name = "60-minute-blitz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.2.2",
    "torch>=2.5.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
]
